#!/bin/bash
# Local two-instance testing lab. No DNS, no TLS, no root.
#
#   alice: domain alice.local  SMTP 127.0.0.1:2525  API 127.0.0.1:8381
#   bob:   domain bob.local    SMTP 127.0.0.1:2526  API 127.0.0.1:8382
#
# Each instance's [delivery] smarthost points at the other's SMTP port, so
# alice->bob and bob->alice deliver over real SMTP with zero MX/DNS lookups.
# State lives under .lab/ (gitignored). See docs/LOCAL_TESTING.md.
#
# Written for macOS /bin/bash 3.2: no associative arrays, no ${var^^}.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
BINARY="${OWNEY_BIN:-$ROOT/target/debug/owneyd}"
LAB="$ROOT/.lab"
FED_OVERRIDES="alice.local=http://127.0.0.1:8381,bob.local=http://127.0.0.1:8382"

usage() {
    cat <<'EOF'
Usage: scripts/lab.sh <command> [args]

Lifecycle
  build                     cargo build the owneyd debug binary
  up [--fresh]              init + start alice.local and bob.local (background)
  down                      stop both instances (clean SIGINT shutdown)
  status                    pids, ports, health, accounts, tokens
  reset                     down + wipe all .lab/ state
  logs <alice|bob> [-f]     show (or follow) an instance's server log

Mail
  send <alice|bob> <plain|newsletter|invite> [--from addr] [--subject subj]
                            inject a fixture via SMTP as an external sender
  send-raw <alice|bob> <file> [--from addr] [--to addr]
                            inject a raw RFC 5322 file via SMTP
  send-between <alice|bob> <alice|bob> [--subject subj] [--body text]
                            real submit -> queue -> smarthost delivery
  inbox <alice|bob> [mailbox] [limit]    list messages (inbox|screener|junk|sent)
  show <alice|bob> <email_id>            print a stored message (raw RFC 5322)
  queue <alice|bob>                      pending outbound deliveries

JMAP
  token <alice|bob>         print the instance's bearer token
  session <alice|bob>       GET /.well-known/jmap, pretty-printed
  jmap <alice|bob> <Method> [json-args]
                            one-shot JMAP call; the string $ACCOUNT_ID inside
                            json-args is replaced with the real account id
  hosts                     print /etc/hosts lines needed by real JMAP clients

Anything else
  admin <alice|bob> <args..>   owneyd admin passthrough for this instance

Notes
  - First mail from a new sender lands in the *screener* mailbox, not inbox
    (deterministic HEY-style screening). Try: lab.sh inbox alice screener
  - Self-send (alice->alice) is unsupported: the smarthost routes ALL
    outbound to the peer, which rejects foreign recipients.
EOF
    exit 1
}

die() { echo "lab.sh: $*" >&2; exit 1; }

# ---- per-instance lookups (bash 3.2: functions, not associative arrays) ----
check_instance() { case "$1" in alice|bob) ;; *) die "unknown instance '$1' (want alice or bob)" ;; esac; }
smtp_port() { case "$1" in alice) echo 2525 ;; bob) echo 2526 ;; esac; }
api_port()  { case "$1" in alice) echo 8381 ;; bob) echo 8382 ;; esac; }
peer_smtp() { case "$1" in alice) echo 2526 ;; bob) echo 2525 ;; esac; }
domain_of() { echo "$1.local"; }
account_of() { echo "$1@$1.local"; }
display_name() { case "$1" in alice) echo Alice ;; bob) echo Bob ;; esac; }
cfg() { echo "$LAB/$1/mailserver.toml"; }

own() {
    local i="$1"; shift
    "$BINARY" --config "$(cfg "$i")" "$@"
}

need_binary() {
    [ -x "$BINARY" ] || die "no binary at $BINARY — run: scripts/lab.sh build"
}

need_python() {
    command -v python3 >/dev/null || die "python3 is required"
}

# ---- config ---------------------------------------------------------------
write_config() {
    local i="$1"
    mkdir -p "$LAB/$i/data"
    cat > "$(cfg "$i")" <<EOF
# Generated by scripts/lab.sh — regenerated on every \`lab.sh up\`.
[server]
domain = "$(domain_of "$i")"
hostname = "mail.$(domain_of "$i")"

[storage]
data_dir = "$LAB/$i/data"

[smtp]
listen = ["127.0.0.1:$(smtp_port "$i")"]

[delivery]
# Static route: ALL outbound goes to the peer instance. No MX/DNS lookups.
smarthost = "127.0.0.1:$(peer_smtp "$i")"
allow_invalid_certs = true
# Short poll so mail queued by the admin CLI is picked up quickly.
poll_interval_secs = 2

[api]
listen = "127.0.0.1:$(api_port "$i")"
# Logical host = federation identity (the port is stripped for identity, but
# kept in the JMAP session apiUrl so real clients can reach it once
# /etc/hosts maps $(domain_of "$i") -> 127.0.0.1; see \`lab.sh hosts\`).
public_url = "http://$(domain_of "$i"):$(api_port "$i")"

[ai]
# provider "none": deterministic skills only (screener, unsubscribe,
# calendar-invite detection) — no API key needed. NOTE: the screener routes
# FIRST-contact mail to the \`screener\` mailbox. Set enabled = false to turn
# the screener off (unsubscribe/calendarInvite detection still runs).
enabled = true
provider = "none"
model = ""
base_url = ""
api_key_env = "UNSET_LAB_KEY"

[oidc]
# OIDC provider on. http://<host>:<port> is a secure context for WebAuthn only
# on localhost; the lab maps the logical host to 127.0.0.1 (see \`lab.sh hosts\`).
enabled = true

[log]
filter = "info"
EOF
}

# ---- lifecycle ------------------------------------------------------------
pid_of() {
    local pidfile="$LAB/$1/owneyd.pid"
    [ -f "$pidfile" ] || return 1
    local pid
    pid="$(cat "$pidfile")"
    kill -0 "$pid" 2>/dev/null || return 1
    echo "$pid"
}

port_free_or_ours() {
    local i="$1" port="$2"
    if nc -z 127.0.0.1 "$port" 2>/dev/null; then
        pid_of "$i" >/dev/null || die "port $port is in use by something that isn't the lab's $i instance"
    fi
}

wait_healthz() {
    local i="$1" port n=0
    port="$(api_port "$i")"
    while ! curl -sf "http://127.0.0.1:$port/healthz" >/dev/null 2>&1; do
        n=$((n + 1))
        [ "$n" -ge 60 ] && die "$i did not become healthy on :$port (see: scripts/lab.sh logs $i)"
        sleep 0.5
    done
}

init_instance() {
    local i="$1" acct
    acct="$(account_of "$i")"
    write_config "$i"
    local accounts
    accounts="$(own "$i" admin accounts 2>/dev/null || true)"
    if ! echo "$accounts" | grep -q "$acct"; then
        own "$i" admin create-account "$acct" --name "$(display_name "$i")" >/dev/null
        echo "created account $acct"
    fi
    if [ ! -f "$LAB/$i/token" ]; then
        own "$i" admin token "$acct" --name lab 2>/dev/null > "$LAB/$i/token"
        chmod 600 "$LAB/$i/token"
        echo "minted API token for $acct -> .lab/$i/token"
    fi
}

start_instance() {
    local i="$1"
    if pid_of "$i" >/dev/null; then
        echo "$i already running (pid $(pid_of "$i"))"
        return 0
    fi
    port_free_or_ours "$i" "$(smtp_port "$i")"
    port_free_or_ours "$i" "$(api_port "$i")"
    (
        cd "$LAB/$i"
        OWNEY_FEDERATION_ENABLED=1 \
        OWNEY_FEDERATION_ALLOW_PRIVATE_IPS=1 \
        OWNEY_FEDERATION_URL_OVERRIDES="$FED_OVERRIDES" \
        OWNEY_FEDERATION_SYNC_INTERVAL_SECS=10 \
        nohup "$BINARY" --config "$(cfg "$i")" serve >> server.log 2>&1 &
        echo $! > owneyd.pid
    )
    wait_healthz "$i"
    echo "$i up: smtp 127.0.0.1:$(smtp_port "$i")  api http://127.0.0.1:$(api_port "$i")  (pid $(pid_of "$i"))"
}

stop_instance() {
    local i="$1" pid n=0
    pid="$(pid_of "$i")" || { echo "$i not running"; rm -f "$LAB/$i/owneyd.pid"; return 0; }
    kill -INT "$pid" 2>/dev/null || true
    while kill -0 "$pid" 2>/dev/null; do
        n=$((n + 1))
        if [ "$n" -ge 10 ]; then
            echo "$i did not exit on SIGINT; killing"
            kill -KILL "$pid" 2>/dev/null || true
            break
        fi
        sleep 0.5
    done
    rm -f "$LAB/$i/owneyd.pid"
    echo "$i stopped"
}

cmd_build() {
    (cd "$ROOT" && cargo build --bin owneyd)
}

cmd_up() {
    if [ "${1:-}" = "--fresh" ]; then
        cmd_down || true
        rm -rf "$LAB"
        echo "wiped .lab/"
    fi
    need_binary
    need_python
    mkdir -p "$LAB/alice" "$LAB/bob"
    init_instance alice
    init_instance bob
    start_instance alice
    start_instance bob
    echo
    echo "Lab is up. Try:"
    echo "  scripts/lab.sh send alice invite      # fixture in via SMTP"
    echo "  scripts/lab.sh inbox alice screener   # first contact lands here"
    echo "  scripts/lab.sh jmap alice Email/query '{\"accountId\":\"\$ACCOUNT_ID\"}'"
    echo "  scripts/lab.sh send-between alice bob # real cross-instance delivery"
}

cmd_down() {
    stop_instance alice
    stop_instance bob
}

cmd_reset() {
    cmd_down || true
    rm -rf "$LAB"
    echo "wiped .lab/"
}

cmd_status() {
    local i pid
    for i in alice bob; do
        if pid="$(pid_of "$i")"; then
            local health="down"
            curl -sf "http://127.0.0.1:$(api_port "$i")/healthz" >/dev/null 2>&1 && health="ok"
            echo "$i: running (pid $pid)  smtp :$(smtp_port "$i")  api :$(api_port "$i")  healthz $health"
        else
            echo "$i: stopped"
        fi
        if [ -f "$(cfg "$i")" ] && [ -x "$BINARY" ]; then
            own "$i" admin accounts 2>/dev/null | sed 's/^/    /' || true
        fi
        [ -f "$LAB/$i/token" ] && echo "    token: .lab/$i/token"
    done
}

cmd_logs() {
    local i="${1:-}"; check_instance "$i"
    local log="$LAB/$i/server.log"
    [ -f "$log" ] || die "no log at $log"
    if [ "${2:-}" = "-f" ]; then tail -f "$log"; else tail -100 "$log"; fi
}

# ---- SMTP fixture injection -------------------------------------------------
# Sends via python3 stdlib so raw sockets/TLS/quoting are a non-issue.
smtp_inject() {
    local i="$1" fixture="$2" from="$3" subject="$4" rawfile="${5:-}" rawto="${6:-}"
    need_python
    LAB_SMTP_PORT="$(smtp_port "$i")" \
    LAB_TO="${rawto:-$(account_of "$i")}" \
    LAB_FROM="$from" \
    LAB_SUBJECT="$subject" \
    LAB_FIXTURE="$fixture" \
    LAB_RAWFILE="$rawfile" \
    python3 - <<'PYEOF'
import os, smtplib, sys, uuid
from email.message import EmailMessage
from email.utils import formatdate

port = int(os.environ["LAB_SMTP_PORT"])
to = os.environ["LAB_TO"]
sender = os.environ["LAB_FROM"]
subject = os.environ["LAB_SUBJECT"]
fixture = os.environ["LAB_FIXTURE"]
rawfile = os.environ["LAB_RAWFILE"]

def base(subject):
    msg = EmailMessage()
    msg["From"] = sender
    msg["To"] = to
    msg["Subject"] = subject
    msg["Date"] = formatdate(localtime=False)
    msg["Message-ID"] = f"<lab-{uuid.uuid4()}@external.test>"
    return msg

if fixture == "raw":
    with open(rawfile, "rb") as f:
        data = f.read()
    s = smtplib.SMTP("127.0.0.1", port, timeout=10)
    s.sendmail(sender, [to], data)
    s.quit()
    print(f"raw message from {rawfile} -> {to}")
    sys.exit(0)

if fixture == "plain":
    msg = base(subject or "Hello from the lab")
    msg.set_content("Just a plain test message.\n")
elif fixture == "newsletter":
    msg = base(subject or "Weekly Lab Digest")
    msg["List-Unsubscribe"] = "<https://news.external.test/unsub/one?u=lab>, <mailto:unsub@external.test>"
    msg["List-Unsubscribe-Post"] = "List-Unsubscribe=One-Click"
    msg.set_content("Lab news, week after week.\nUnsubscribe any time.\n")
elif fixture == "invite":
    msg = base(subject or "BBQ on Friday")
    msg.set_content("Come over to my BBQ Friday at 7pm!\n")
    ics = (
        "BEGIN:VCALENDAR\r\n"
        "VERSION:2.0\r\n"
        "PRODID:-//lab//EN\r\n"
        "METHOD:REQUEST\r\n"
        "BEGIN:VEVENT\r\n"
        f"UID:lab-{uuid.uuid4()}@external.test\r\n"
        "SUMMARY:BBQ at\r\n"
        " Carol's place\r\n"
        "LOCATION:Backyard\r\n"
        f"ORGANIZER:mailto:{sender}\r\n"
        "DTSTART:20260717T190000Z\r\n"
        "DTEND:20260717T220000Z\r\n"
        "END:VEVENT\r\n"
        "END:VCALENDAR\r\n"
    )
    msg.add_attachment(
        ics.encode(), maintype="text", subtype="calendar",
        filename="invite.ics", params={"method": "REQUEST"},
    )
else:
    sys.exit(f"unknown fixture {fixture}")

s = smtplib.SMTP("127.0.0.1", port, timeout=10)
s.send_message(msg)
s.quit()
print(f"{fixture} fixture from {sender} -> {to}")
PYEOF
}

cmd_send() {
    local i="${1:-}" fixture="${2:-}"; check_instance "$i"
    case "$fixture" in plain|newsletter|invite) ;; *) die "fixture must be plain|newsletter|invite" ;; esac
    shift 2
    local from="carol@external.test" subject=""
    while [ $# -gt 0 ]; do
        case "$1" in
            --from) from="$2"; shift 2 ;;
            --subject) subject="$2"; shift 2 ;;
            *) die "unknown flag $1" ;;
        esac
    done
    smtp_inject "$i" "$fixture" "$from" "$subject"
}

cmd_send_raw() {
    local i="${1:-}" file="${2:-}"; check_instance "$i"
    [ -f "$file" ] || die "no such file: $file"
    shift 2
    local from="carol@external.test" to=""
    while [ $# -gt 0 ]; do
        case "$1" in
            --from) from="$2"; shift 2 ;;
            --to) to="$2"; shift 2 ;;
            *) die "unknown flag $1" ;;
        esac
    done
    smtp_inject "$i" raw "$from" "" "$file" "$to"
}

cmd_send_between() {
    local from_i="${1:-}" to_i="${2:-}"
    check_instance "$from_i"; check_instance "$to_i"
    [ "$from_i" = "$to_i" ] && die "self-send is unsupported: the smarthost routes ALL outbound to the peer instance, which rejects recipients for other domains. Use 'send $from_i <fixture>' to test inbound instead."
    shift 2
    local subject="Hello from $(account_of "$from_i")" body="Sent across the lab at $(date)."
    while [ $# -gt 0 ]; do
        case "$1" in
            --subject) subject="$2"; shift 2 ;;
            --body) body="$2"; shift 2 ;;
            *) die "unknown flag $1" ;;
        esac
    done
    own "$from_i" admin send "$(account_of "$from_i")" "$(account_of "$to_i")" \
        --subject "$subject" --body "$body"
    echo "queued; serve's delivery worker polls every 2s — check: scripts/lab.sh inbox $to_i screener"
}

cmd_inbox() {
    local i="${1:-}"; check_instance "$i"
    local mailbox="${2:-inbox}" limit="${3:-20}"
    own "$i" admin inbox "$(account_of "$i")" --mailbox "$mailbox" --limit "$limit"
    if [ "$mailbox" = "inbox" ]; then
        local screener_count
        screener_count="$(own "$i" admin inbox "$(account_of "$i")" --mailbox screener --limit 50 2>/dev/null | wc -l | tr -d ' ')"
        if [ "$screener_count" -gt 0 ]; then
            echo "(hint: $screener_count message(s) in the screener — first-contact senders land there: scripts/lab.sh inbox $i screener)"
        fi
    fi
}

cmd_show()  { local i="${1:-}"; check_instance "$i"; own "$i" admin show "${2:?email id required}"; }
cmd_queue() { local i="${1:-}"; check_instance "$i"; own "$i" admin queue; }
cmd_admin() { local i="${1:-}"; check_instance "$i"; shift; own "$i" admin "$@"; }
cmd_token() { local i="${1:-}"; check_instance "$i"; cat "$LAB/$i/token"; }

bearer() {
    local i="$1"
    [ -f "$LAB/$i/token" ] || die "no token for $i — run: scripts/lab.sh up"
    cat "$LAB/$i/token"
}

cmd_session() {
    local i="${1:-}"; check_instance "$i"
    curl -sf -H "Authorization: Bearer $(bearer "$i")" \
        "http://127.0.0.1:$(api_port "$i")/.well-known/jmap" | python3 -m json.tool
}

account_id_of() {
    local i="$1" cache="$LAB/$i/account_id"
    if [ ! -f "$cache" ]; then
        curl -sf -H "Authorization: Bearer $(bearer "$i")" \
            "http://127.0.0.1:$(api_port "$i")/.well-known/jmap" \
            | python3 -c 'import json,sys; s=json.load(sys.stdin); print(s["primaryAccounts"]["urn:ietf:params:jmap:mail"])' \
            > "$cache"
    fi
    cat "$cache"
}

cmd_jmap() {
    local i="${1:-}"; check_instance "$i"
    local method="${2:?JMAP method required (e.g. Email/query)}"
    local args="${3:-}"
    [ -n "$args" ] || args='{}'
    need_python
    local account_id
    account_id="$(account_id_of "$i")"
    LAB_METHOD="$method" LAB_ARGS="$args" LAB_ACCOUNT_ID="$account_id" python3 - <<'PYEOF' \
        | curl -sf -X POST "http://127.0.0.1:$(api_port "$i")/jmap/api" \
            -H "Authorization: Bearer $(bearer "$i")" \
            -H "Content-Type: application/json" \
            --data-binary @- \
        | python3 -m json.tool
import json, os, sys
args = os.environ["LAB_ARGS"].replace("$ACCOUNT_ID", os.environ["LAB_ACCOUNT_ID"])
try:
    parsed = json.loads(args)
except json.JSONDecodeError as err:
    sys.exit(f"bad json-args: {err}")
body = {
    "using": [
        "urn:ietf:params:jmap:core",
        "urn:ietf:params:jmap:mail",
        "urn:ietf:params:jmap:submission",
        "urn:owney:params:jmap:calendar",
        "urn:owney:params:jmap:attributes",
    ],
    "methodCalls": [[os.environ["LAB_METHOD"], parsed, "c1"]],
}
print(json.dumps(body))
PYEOF
}

cmd_hosts() {
    cat <<'EOF'
# Only needed to point REAL JMAP clients at the lab (the session apiUrl uses
# logical hostnames). lab.sh itself always talks to 127.0.0.1 directly.
# Append to /etc/hosts:
127.0.0.1 alice.local mail.alice.local
127.0.0.1 bob.local mail.bob.local
EOF
}

# ---- dispatch ---------------------------------------------------------------
cmd="${1:-help}"
shift || true
case "$cmd" in
    build) cmd_build "$@" ;;
    up) cmd_up "$@" ;;
    down) cmd_down "$@" ;;
    status) cmd_status "$@" ;;
    reset) cmd_reset "$@" ;;
    logs) cmd_logs "$@" ;;
    send) cmd_send "$@" ;;
    send-raw) cmd_send_raw "$@" ;;
    send-between) cmd_send_between "$@" ;;
    inbox) cmd_inbox "$@" ;;
    show) cmd_show "$@" ;;
    queue) cmd_queue "$@" ;;
    token) cmd_token "$@" ;;
    session) cmd_session "$@" ;;
    jmap) cmd_jmap "$@" ;;
    hosts) cmd_hosts "$@" ;;
    admin) cmd_admin "$@" ;;
    help|-h|--help|*) usage ;;
esac
